name: Static Analyzers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}
      - name: clang-format
        uses: DoozyX/clang-format-lint-action@v0.8
        with:
          source: './src'
          exclude: '.git'
          extensions: 'cpp,hpp,cxx,hxx,cxx.in'
          clangFormatVersion: 10
          style: file

