name: cppcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run cppcheck
      shell: bash
      run: |
          sudo snap install cppcheck
          cppcheck \
            --suppress=missingInclude \
            --suppress=noExplicitConstructor \
            --suppress=useStlAlgorithm \
            --inline-suppr \
            --inconclusive \
            --enable=all \
            --template='[{file}:{line}]:({severity}),[{id}],{message}' \
            --force -q -j $(nproc) \
            -i ./src/qtwinmigrate \
            ./src 2>&1 | tee cppcheck.txt

    - name: Parse and colorize cppcheck
      shell: bash
      run: python ./ci/colorize_cppcheck_results.py

    - name: Upload cppcheck results as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
          name: OpenStudioApplication-${{ github.sha }}-cppcheck_results.txt
          path: cppcheck.txt
